development:
  adapter: mysql2
  database: gbra_development
  username: gbra
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

acceptance:
  adapter: mysql2
  database: gbra_test
  username: ror_test
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

test:
  adapter: mysql2
  database: gbra_test
  username: ror_test
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

staging:
  adapter: mysql2
  database: gbra_staging
  username: gbra
  encoding: utf8
  host: localhost
  reconnect: false
  pool: 5

production:
  adapter: mysql2
  database: gbra
  username: gbra
  password: MNKPR6TCOLysqJ3
  encoding: utf8
  host: localhost
  reconnect: false
  pool: 5
